spring:
  application:
    name: application
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:mortgage-db
    driver-class-name: org.h2.Driver



